"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""
import glob

from setuptools import setup

APP = ['angkor_typing.py']
DATA_FILES = [
    ("fonts", glob.glob('fonts/*')),
    ("infrastructure", glob.glob('infrastructure/*')),
    ("src", glob.glob('src/*')),
    ("utils", glob.glob('utils/*')),
    ("words", glob.glob('words/*')),
]
OPTIONS = {}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app', 'pygame'],
)
